FROM node:alpine

WORKDIR "/app"

RUN ["apk", "add", "--update", "--no-cache", "git"]

RUN ["npm", "install", "-g", "create-react-app"]

RUN ["create-react-app", "reactapp"]

WORKDIR "/app/reactapp"

RUN ["npm", "install"]

CMD ["npm", "run", "start"]
