version: 2
jobs:
  build_deploy:
    working_directory: /app
    docker:
      - image: docker:git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache --update \
              python3-dev \
              py3-setuptools \
              libffi-dev \
              openssl-dev \
              gcc \
              libc-dev \
              make
            pip3 install \
              docker-compose \
              awscli \
              awsebcli --upgarde
      - run:
          name: Build application Docker image (dev)
          command: |
            docker build -t aesthet/react -f Dockerfile.dev .
      - run:
          name: Run tests
          command: |
            docker-compose -f docker-compose.yml up
      - run:
          name: Create AWS credentials manually
          command: |
            mkdir ~/.aws
            touch ~/.aws/config
            chmod 600 ~/.aws/config
            echo "[profile dockercircleci]" > ~/.aws/config
            echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/config
            echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/config
      - run:
          name: Deploy to EB if branch is Master
          command: |
             eb use Dockerweb-env --profile dockercircleci
             eb deploy -v --staged --profile dockercircleci
workflows:
  version: 2
  build-deploy:
    jobs:
      - build_deploy:
          filters:
            branches:
              only: 
                - master
                - develop
